run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    - maligned # deprecated
    - nosnakecase # deprecated
    - interfacer # deprecated
    - exhaustivestruct # deprecated
    - ifshort # deprecated
    - golint # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - deadcode # deprecated
    - varcheck # deprecated
    - depguard
    - exhaustruct
    - wsl
    - varnamelen
    - gofumpt
    - gci
    - gofmt
    - goimports
linters-settings:
  funlen:
    lines: 100
    statements: 40
  nakedret:
    max-func-lines: 0
  lll:
    line-length: 140
  gocyclo:
    min-complexity: 20
  golint:
    min-confidence: 0
  dupl:
    threshold: 100
  govet:
    check-shadowing: true
  wrapcheck:
    # An array of strings that specify substrings of signatures to ignore.
    # If this set, it will override the default set of ignored signatures.
    # See https://github.com/tomarrell/wrapcheck#configuration for more information.
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - errors.Join(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
output:
  print-issued-lines: false
