// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ceperapl/requester/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// TaskRepository is an autogenerated mock type for the TaskRepository type
type TaskRepository struct {
	mock.Mock
}

// CreateTaskResult provides a mock function with given fields: ctx, taskResult
func (_m *TaskRepository) CreateTaskResult(ctx context.Context, taskResult *domain.TaskResult) error {
	ret := _m.Called(ctx, taskResult)

	if len(ret) == 0 {
		panic("no return value specified for CreateTaskResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TaskResult) error); ok {
		r0 = rf(ctx, taskResult)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTaskResult provides a mock function with given fields: ctx, taskID
func (_m *TaskRepository) GetTaskResult(ctx context.Context, taskID string) (*domain.TaskResult, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskResult")
	}

	var r0 *domain.TaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.TaskResult, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.TaskResult); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TaskResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTaskResult provides a mock function with given fields: ctx, taskResult
func (_m *TaskRepository) UpdateTaskResult(ctx context.Context, taskResult *domain.TaskResult) error {
	ret := _m.Called(ctx, taskResult)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TaskResult) error); ok {
		r0 = rf(ctx, taskResult)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskRepository creates a new instance of TaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRepository {
	mock := &TaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
