// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ceperapl/requester/pkg/domain"
	mock "github.com/stretchr/testify/mock"

	mq "github.com/ceperapl/requester/pkg/mq"
)

// TaskQueuer is an autogenerated mock type for the TaskQueuer type
type TaskQueuer struct {
	mock.Mock
}

// Consume provides a mock function with given fields: ctx, doFunc
func (_m *TaskQueuer) Consume(ctx context.Context, doFunc mq.ProcessingFunc) error {
	ret := _m.Called(ctx, doFunc)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, mq.ProcessingFunc) error); ok {
		r0 = rf(ctx, doFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Publish provides a mock function with given fields: ctx, task
func (_m *TaskQueuer) Publish(ctx context.Context, task domain.Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskQueuer creates a new instance of TaskQueuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskQueuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskQueuer {
	mock := &TaskQueuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
