// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ceperapl/requester/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// TaskExecutor is an autogenerated mock type for the TaskExecutor type
type TaskExecutor struct {
	mock.Mock
}

// ExecuteTask provides a mock function with given fields: ctx, task
func (_m *TaskExecutor) ExecuteTask(ctx context.Context, task domain.Task) (*domain.TaskResult, error) {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteTask")
	}

	var r0 *domain.TaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Task) (*domain.TaskResult, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Task) *domain.TaskResult); ok {
		r0 = rf(ctx, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TaskResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Task) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskExecutor creates a new instance of TaskExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskExecutor {
	mock := &TaskExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
