// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ceperapl/requester/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// TaskUsecaser is an autogenerated mock type for the TaskUsecaser type
type TaskUsecaser struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: ctx, task
func (_m *TaskUsecaser) CreateTask(ctx context.Context, task domain.Task) (string, error) {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Task) (string, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Task) string); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Task) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskResult provides a mock function with given fields: ctx, id
func (_m *TaskUsecaser) GetTaskResult(ctx context.Context, id string) (*domain.TaskResult, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskResult")
	}

	var r0 *domain.TaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.TaskResult, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.TaskResult); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TaskResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessTask provides a mock function with given fields: ctx, task
func (_m *TaskUsecaser) ProcessTask(ctx context.Context, task domain.Task) (*domain.TaskResult, error) {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for ProcessTask")
	}

	var r0 *domain.TaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Task) (*domain.TaskResult, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Task) *domain.TaskResult); ok {
		r0 = rf(ctx, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TaskResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Task) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskUsecaser creates a new instance of TaskUsecaser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskUsecaser(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskUsecaser {
	mock := &TaskUsecaser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
